### ISSUE TITLE
justinmimbs/elm-date-extra

### ISSUE THREAD

**Issue by andys8** [kraklin/elm-readiness#1]
### Marked red
![image](https://user-images.githubusercontent.com/13085980/45752194-f3c5e280-bc14-11e8-8961-2a8c8ed65c0d.png)

The documentation is telling it is replaced by multiple other libraries.

https://github.com/justinmimbs/elm-date-extra/blob/master/README.md#upgrading-to-elm-019

Since the readiness helper is designed to propose a single alternative package, we could go with `justinmimbs/date` or change the design to allow more packages.

**Comment by kraklin** [comment]
Great idea with multiple packages, it is implemented now. Thanks @andys8
